language: scala
sudo: required
scala:
  - 2.11.8
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.coursier/cache	
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
env:
  global:
    JAVA_OPTS=-Xmx2g
    SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:MaxPermSize=512m"
script:
  - sbt test