resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("com.typesafe.sbt"    % "sbt-native-packager" % "1.7.0")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly"        % "0.14.10")
addSbtPlugin("com.eed3si9n"        % "sbt-buildinfo"       % "0.9.0")
addSbtPlugin("se.marcuslonnberg"   % "sbt-docker"          % "1.5.0")
addSbtPlugin("com.47deg"           % "sbt-org-policies"    % "0.13.3")
addSbtPlugin("com.geirsson"        % "sbt-ci-release"      % "1.5.3")
addSbtPlugin("org.scalameta"       % "sbt-mdoc"            % "2.1.5")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"        % "2.3.3")
addSbtPlugin("com.alejandrohdezma" % "sbt-mdoc-toc"        % "0.2")
