resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.5.2")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "0.14.10")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.9.0")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"          % "1.5.0")
addSbtPlugin("com.47deg"         % "sbt-org-policies"    % "0.12.0-M3")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "3.0.2")
